### ISSUE TITLE
Placeholder text not being replaced for special Thaumcraft entries

### ISSUE THREAD

**Issue by LyraelRayne** [SnowShock35/Obscurity#111] opened 2015-07-17 11:50 UTC
The text placeholders are not being replaced with text in the Obscurity specific tab of the Thaumcraft book (or at least I assume that's what that tab is for as one of the items is from Quadrum). 

![image](https://cloud.githubusercontent.com/assets/11632412/8746543/a0f3e068-2ccd-11e5-9250-efe9b7c3f6bb.png)

**Comment by SnowShock35** [comment] 2015-07-17 14:11
@LyraelRayne Can you try relog and tell me if it fixes the issue?

**Comment by LyraelRayne** [comment] 2015-07-17 14:47
I just closed the game and started it again. No change. I'm on 1.1.13_Beta btw.

**Comment by SnowShock35** [comment] 2015-07-17 18:41
@LyraelRayne 
What language do you have the game in?

**Comment by LyraelRayne** [comment] 2015-07-18 00:53
English (UK). Changed to English (US) and it is working now. Wonder why it's set like that. Perhaps Curse set it because my OS is on English (AU). 

Is there meant to be no picture on the recipe page for glowstone? I presume so as the recipe is written out in text but figured I'd mention it just in case.

**Comment by SnowShock35** [comment] 2015-07-18 10:48
@LyraelRayne Okay Ik what the issue is here. For now please use English US it's not that much different. Will get fixed for next version. 

As for the recipe thing because thaumcraft adds a glowstone recipe already for the crucible if I try add it to the thaumonicon It will add that one instead of ours. Talking to one of the authors of ModTweaker 2 should have a fix for this soon. 

Thanks again for you amazing help @LyraelRayne In fact if you would like to you may join the testing team. Just send me your email address to xsnowshockx35@gmail.com and I will add you. Entirely up to you if you want to be apart of it or not but, you are fantastic at it from two of the issues you've contributed to so far so I think you would be great for the position ;)

**Comment by SnowShock35** [comment] 2015-07-19 10:57
@LyraelRayne Okay I've fixed this but, if u change language during the game being loaded without restarting you will have localization issues with everything because of the way minetweaker works unfortunately (

**Comment by SnowShock35** [comment] 2015-07-22 10:08
Fixed in 1.1.15_Beta

**Closed by SnowShock35** 2015-07-22 10:08 UTC
Labels: Bug, Discussion, More Information Required
