### ISSUE TITLE
Quest issues

### ISSUE THREAD

**Issue by Sensei-Z** [SnowShock35/Obscurity#67] opened 2015-07-01 18:32 UTC
The quest in the first group in which you have to craft a magma crucible does not complete upon crafting one.

The lava quest in which you submit 100 buckets only accepts "lava source" the item not the liquid. I had to cheat and submit 100 lava source blocks to complete the quest.

AFAIK there is no quartz from NNN in the world (this was generated in 1.1.10 beta)

The "pipes aint pipes" quest makes you craft 16 sets of the itemducts/conduits, not the items.

As an aside, how do I add labels to this?

**Comment by AKTheKnight** [comment] 2015-07-01 19:17
Thanks for bringing these to our attention, I will make sure these are fixed for the next update.

The quartz issue is a known one and is one of the driving reasons why we are redoing the map for the next major update.

Only certain people are able to add labels

**Comment by SnowShock35** [comment] 2015-07-01 19:38
So as AK said all of those will be fixed in the next version and the quartz generation is already on our to do fix list ;)

**Comment by eslachance** [comment] 2015-07-01 20:02
Wouldn't pumping lava into the QDS using a duct count as source lava?

**Comment by SnowShock35** [comment] 2015-07-01 20:07
@eslachance is right. This was how the quest was intended. If this does not work then I will continue to look into it otherwise I'm pretty sure the QED is required for that task ;)

**Comment by johnnymobbins** [comment] 2015-07-08 10:34
Magma crucible quest removed. Update in next version.

All other issues either fixed or will be in new map.

**Comment by SnowShock35** [comment] 2015-07-16 07:45
@johnnymobbins Please could you look at this mate and confirm whether it's done or not ;)

**Closed** 2015-07-16 11:50 UTC
Labels: Bug, Quest Related
