### ISSUE TITLE
Flux-Infused tools not working?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#82] opened 2015-07-07 23:05 UTC
When I attempt too use the flux-infused pickaxe or shovel (not tried the axe yet) it will not mine. At all.
It does not say on the tool tip "This tool cannot mine anything" so I have no idea what the issue is.

**Comment by SnowShock35** [comment] 2015-07-08 09:03
Will fix for the next version, sorry for this ;)

**Comment by Insufficient-Charge** [comment] 2015-07-08 13:41
Its fine, just wanted to use them after completing the quest and found out they were useless :/

**Comment by SnowShock35** [comment] 2015-07-14 19:06
@Insufficient-Charge Okay so this problem is caused by SquidUtils and until the mod updates I can't do anything about it. Will try fix it for 1.1.13 but no garentees

**Comment by SnowShock35** [comment] 2015-07-15 11:30
@johnnymobbins is disabling these quests for now will re-enable for 1.2.0

Sorry about this

**Comment by Insufficient-Charge** [comment] 2015-07-17 22:53
Its fine . . . as long as I get to use that pickaxe eventualy I'm good :D

**Comment by SnowShock35** [comment] 2015-07-18 10:41
This will be fixed for 1.1.15_Beta ;)

**Comment by SnowShock35** [comment] 2015-07-22 10:07
Fixed in 1.1.15_Beta

**Closed by SnowShock35** 2015-07-22 10:07 UTC
Labels: Bug, Discussion

**Comment by LyraelRayne** [comment] 2015-07-24 14:07
@johnnymobbins you might want to re-enable the quest for these now that the tools are working.
