### ISSUE TITLE
Crafting tasks don't correctly detect when recipe returns more than 1 of an item

### ISSUE THREAD

**Issue by wlhlm** [SnowShock35/Obscurity#208] opened 2015-09-06 16:05 UTC
For certain items, the quest book won't correctly detect the amount of an item I have crafted. This happened to me when the recipe returns more than one item, but the book would only detect one instead.

The problem occurred in the quests:

 - Holy Boom
![2015-09-06_16 30 37](https://cloud.githubusercontent.com/assets/1928113/9705293/9e6d5278-54c0-11e5-86eb-a899ab27c638.png)
  - Recipe returns 4 grenades, gets detected as 1

 - Pipes ain't Pipes
![2015-09-06_17 47 40](https://cloud.githubusercontent.com/assets/1928113/9705294/9e6ddaae-54c0-11e5-8115-117b8d126449.png)
  - Recipe returns 6, I crafted 18 (3x), gets detected as 3

 - More Ammo (don't have a screenshot for it)
  - Recipe returns 4 items, gets detected as 1

In the screenshots above you can find the items I had to craft for the quest in the hotbar.

Minecraft version: 1.7.10
Obscurity version: 1.1.16_Beta
Forge version: 10.13.4.1448
Java version: 1.8.0_60
OS version: Win7 amd64

**Comment by LyraelRayne** [comment] 2015-09-07 11:19
This is essentially a duplicate of https://github.com/SnowShock35/Obscurity/issues/161 (same root cause). It's a known issue with HQM. Not much we can do about it other than changing all the quests to detection mode rather than crafting mode.

There is an open issue on the HQM issue tracker about this https://bitbucket.org/Newcastlegeek/hqm-bugtracker/issues/78/quests-with-multiple-outputs-on-craft-only

**Closed by LyraelRayne** 2015-09-07 11:19 UTC
Labels: Can't Fix, Duplicate, Related - Mod, Related - Quest
