### ISSUE TITLE
Interdiction torch sometimes disappearing?

### ISSUE THREAD

**Issue by Insufficient-Charge** [SnowShock35/Obscurity#91] opened 2015-07-09 20:41 UTC
As I was adventuring out to find the diffrent cubes, one time, I broke my interdiction torch, and it disappeared!

This has happened to me four times now, not liking it :/

Its only sometimes that it "breaks"

**Comment by AKTheKnight** [comment] 2015-07-09 20:51
Ooh interesting. I wonder if snow has this set intentionally. I will ask

**Comment by Insufficient-Charge** [comment] 2015-07-09 21:19
If he did set that, then he is as evil as Eyemaz XD

**Comment by SnowShock35** [comment] 2015-07-12 15:34
@Insufficient-Charge This is strange i have no idea why this is happening. gonna need some more information. Maybe fml-latest log and steps to repeat.

**Comment by Insufficient-Charge** [comment] 2015-07-12 16:29
Mostly sure about this because every time I need to stop dying from the darkness I look for an interdiction torch in my inventory, and its not there. And I play with Nei's "Magnet mode" on so I shouldn't be dropping it, even when it does "break" I go back and look for it.

**Comment by AKTheKnight** [comment] 2015-07-19 11:52
We have been unable to reproduce this issue:

"oh yeah that issue about interdiction torches disappearing. I swear that happened to me the first time I played through, but I placed and broke a few thousand torches today while watching netflix (macro keybind mod FTW!) and I ended up with the same number by the end. In fact if I placed them fast enough (more than once per second) I ended up with a few extra!"

Therefore I am closing this issue, if anyone can reproduce this I will happily reopen it

**Closed by AKTheKnight** 2015-07-19 11:52 UTC
Labels: Bug, Discussion, More Information Required
