### ISSUE TITLE
[Bug] Seriously overpowered spiders!

### ISSUE THREAD

**Issue by SnowShock35** [SnowShock35/Obscurity#77] opened 2015-07-05 17:19 UTC
Have no idea why but several incidents of spiders with huge amounts of life and hits really strong.

**Comment by LyraelRayne** [comment] 2015-07-18 05:35
See my detailed report on https://github.com/rwtema/extrautilities/issues/483 

Appears to be caused by Optifine.

Also for informational purposes, this appears to somewhat affect headcrumbs celebrity mobs as well, although not to the same extent.

**Comment by LyraelRayne** [comment] 2015-08-16 05:54
This issue is caused by optifine. Optifine is not part of the pack. An issue has been logged with Extra Utilities. Closing.

**Closed by LyraelRayne** 2015-08-16 05:54 UTC
Labels: Bug, Can't Fix, Discussion, More Information Required
